id: I4995BD43
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T18:35:35+00:00'
last_modified: '2022-06-07T12:39:43.123188+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN505
  title: ཀློང་ཆེན་སྙིང་ཐིག་རྩ་པོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '3873':
      image_group_id: I3CN4543
      title: ''
      total_pages: 746
      order: 1
      base_file: 3873.txt
    0806:
      image_group_id: I3CN4544
      title: ''
      total_pages: 800
      order: 2
      base_file: 0806.txt
    '3116':
      image_group_id: I3CN4545
      title: ''
      total_pages: 740
      order: 3
      base_file: 3116.txt
    D7CA:
      image_group_id: I3CN4546
      title: ''
      total_pages: 990
      order: 4
      base_file: D7CA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
