id: I4995BD43
legacy_id: P000686
ocr_import_info:
  bdrc_scan_id: W3CN505
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T18:29:03'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T14:46:30.502455+00:00'
last_modified: 2022-09-03 22:47:39.823915
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN505
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN505
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཀློང་ཆེན་སྙིང་ཐིག་རྩ་པོད།
  author: ཀུན་མཁྱེན་འཇིགས་མེད་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.7336826463465105
  ocr_word_median_confidence_index: 0.800000011920929
quality: null
bases:
  I3CN4543:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN4543
      total_pages: 746
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN4543.txt
    statistics:
      ocr_word_median_confidence_index: 0.7799999713897705
      ocr_word_mean_confidence_index: 0.7155001447696235
    legacy_id: v001
  I3CN4545:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN4545
      total_pages: 740
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3CN4545.txt
    statistics:
      ocr_word_median_confidence_index: 0.7799999713897705
      ocr_word_mean_confidence_index: 0.7142589951478384
    legacy_id: v003
  I3CN4546:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN4546
      total_pages: 990
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I3CN4546.txt
    statistics:
      ocr_word_median_confidence_index: 0.8700000047683716
      ocr_word_mean_confidence_index: 0.7933508188781141
    legacy_id: v004
  I3CN4544:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN4544
      total_pages: 800
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3CN4544.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.6882217541433401
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
